#!/bin/bash
# Configure Xorg to use iGPU for display, freeing dGPU for containers
# Run this on akula-prime desktop to enable seamless GPU sharing

set -e

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

echo "🎮 Configure iGPU Display Fallback"
echo "===================================="
echo ""

# Check if running as root
if [ "$EUID" -ne 0 ]; then
    echo -e "${RED}❌ This script must be run as root${NC}"
    echo "Usage: sudo $0"
    exit 1
fi

# Check for iGPU
echo "🔍 Detecting GPUs..."
IGPU_BUS=$(lspci | grep -i "VGA.*Intel" | awk '{print $1}' | head -1)
DGPU_BUS=$(lspci | grep -i "VGA.*NVIDIA" | awk '{print $1}' | head -1)

if [ -z "$IGPU_BUS" ]; then
    echo -e "${RED}❌ No Intel iGPU found${NC}"
    echo "This script requires an integrated GPU."
    echo "For dGPU-only systems, consider resource limits instead."
    exit 1
fi

if [ -z "$DGPU_BUS" ]; then
    echo -e "${YELLOW}⚠️  No NVIDIA dGPU found${NC}"
    echo "Proceeding anyway..."
fi

echo -e "${GREEN}✅ Found iGPU at $IGPU_BUS (Intel)${NC}"
echo -e "${GREEN}✅ Found dGPU at $DGPU_BUS (NVIDIA)${NC}"
echo ""

# Convert bus IDs to proper format (00:02:0 -> PCI:0:2:0)
IGPU_PCI=$(echo "$IGPU_BUS" | sed 's/\([0-9a-f]\+\):\([0-9a-f]\+\)\.\([0-9]\)/PCI:\1:\2:\3/')
DGPU_PCI=$(echo "$DGPU_BUS" | sed 's/\([0-9a-f]\+\):\([0-9a-f]\+\)\.\([0-9]\)/PCI:\1:\2:\3/')

echo "📝 Creating Xorg configuration..."

# Backup existing config if present
if [ -d "/etc/X11/xorg.conf.d" ]; then
    if [ -f "/etc/X11/xorg.conf.d/20-igpu-primary.conf" ]; then
        cp /etc/X11/xorg.conf.d/20-igpu-primary.conf /etc/X11/xorg.conf.d/20-igpu-primary.conf.bak
        echo "   Backed up existing config"
    fi
else
    mkdir -p /etc/X11/xorg.conf.d
fi

# Create Xorg config
cat > /etc/X11/xorg.conf.d/20-igpu-primary.conf << EOF
# iGPU Primary Display Configuration
# Auto-generated by configure-igpu-display.sh
# Date: $(date)

Section "ServerLayout"
    Identifier     "Layout0"
    Screen      0  "iGPU-Screen" 0 0
    Option         "AutoAddGPU" "false"
EndSection

Section "Device"
    Identifier     "iGPU"
    Driver         "intel"
    BusID          "$IGPU_PCI"
    Option         "AccelMethod" "sna"
    Option         "TearFree" "true"
EndSection

Section "Screen"
    Identifier     "iGPU-Screen"
    Device         "iGPU"
    DefaultDepth    24
    SubSection     "Display"
        Depth       24
    EndSubSection
EndSection

Section "Device"
    Identifier     "dGPU"
    Driver         "nvidia"
    BusID          "$DGPU_PCI"
    # Don't use for display, only compute
    Option         "AllowEmptyInitialConfiguration" "True"
EndSection
EOF

echo -e "${GREEN}✅ Created /etc/X11/xorg.conf.d/20-igpu-primary.conf${NC}"
echo ""

# Install Intel drivers if not present
echo "📦 Checking Intel drivers..."
if ! dpkg -l | grep -q xserver-xorg-video-intel; then
    echo "Installing Intel graphics drivers..."
    apt update
    apt install -y xserver-xorg-video-intel
    echo -e "${GREEN}✅ Intel drivers installed${NC}"
else
    echo -e "${GREEN}✅ Intel drivers already installed${NC}"
fi
echo ""

# Show configuration
echo "📋 Configuration Summary:"
echo "   Primary Display: iGPU (Intel) at $IGPU_BUS"
echo "   Compute Only: dGPU (NVIDIA) at $DGPU_BUS"
echo ""

# Prompt for restart
echo -e "${YELLOW}⚠️  Display manager needs to restart for changes to take effect${NC}"
echo ""
read -p "Restart display manager now? (y/N) " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]; then
    echo "🔄 Restarting display manager..."
    
    # Detect display manager
    if systemctl is-active --quiet gdm3; then
        systemctl restart gdm3
    elif systemctl is-active --quiet gdm; then
        systemctl restart gdm
    elif systemctl is-active --quiet lightdm; then
        systemctl restart lightdm
    elif systemctl is-active --quiet sddm; then
        systemctl restart sddm
    else
        echo -e "${YELLOW}⚠️  Could not detect display manager${NC}"
        echo "Please restart manually or reboot the system"
    fi
    
    echo -e "${GREEN}✅ Configuration complete!${NC}"
else
    echo ""
    echo "Configuration saved. Changes will take effect after:"
    echo "  - Restarting display manager: sudo systemctl restart gdm3"
    echo "  - Or rebooting the system"
fi

echo ""
echo "🔍 To verify after restart:"
echo "   glxinfo | grep 'OpenGL renderer'"
echo "   Should show: Intel"
echo ""
echo "📊 To monitor GPU usage:"
echo "   ./tools/monitor-gpu-sharing.sh"
