#!/bin/bash
set -euo pipefail

# Setup SSO for homelab deployment
# This script configures Keycloak, OAuth2-Proxy, and generates all required secrets

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$PROJECT_ROOT"

ENV_FILE="${ENV_FILE:-.env.homelab}"

echo "=== ComfyUI SSO Setup ==="
echo "Environment file: $ENV_FILE"
echo

if [ ! -f "$ENV_FILE" ]; then
    echo "Error: $ENV_FILE not found"
    exit 1
fi

# Generate secrets
echo "[1/6] Generating secure secrets..."
OAUTH2_PROXY_COOKIE_SECRET=$(openssl rand -base64 32 | tr -d '\n' | tr '+/' '-_')
OAUTH2_PROXY_CLIENT_SECRET=$(openssl rand -base64 32 | tr -d '\n' | tr '+/' '-_')
KEYCLOAK_BOOTSTRAP_ADMIN_PASSWORD=$(openssl rand -base64 18 | tr -d '\n' | tr -d '=')
KEYCLOAK_DB_PASSWORD=$(openssl rand -base64 18 | tr -d '\n' | tr -d '=')
SSO_ADMIN_PASS=$(openssl rand -base64 18 | tr -d '\n' | tr -d '=')
SSO_USER1_PASS=$(openssl rand -base64 18 | tr -d '\n' | tr -d '=')
SSO_USER2_PASS=$(openssl rand -base64 18 | tr -d '\n' | tr -d '=')

# Check if SSO config already exists
if grep -q "^SSO_ENABLED=" "$ENV_FILE" 2>/dev/null; then
    echo "⚠️  SSO configuration already exists in $ENV_FILE"
    echo "   Remove existing SSO section before running this script if you want to regenerate."
    exit 1
fi

# Append SSO configuration to env file
echo "[2/6] Updating $ENV_FILE with SSO configuration..."
cat >> "$ENV_FILE" << EOF

# =============================================================================
# === SSO Configuration (Keycloak + OAuth2-Proxy) ===
# =============================================================================
# Generated by tools/setup-sso.sh on $(date -u +"%Y-%m-%d %H:%M:%S UTC")

# Enable SSO features
SSO_ENABLED=1
KEYCLOAK_ENABLED=1

# OAuth2 Proxy OIDC Client
OAUTH2_PROXY_CLIENT_ID=comfyui-ingress
OAUTH2_PROXY_CLIENT_SECRET=${OAUTH2_PROXY_CLIENT_SECRET}
OAUTH2_PROXY_COOKIE_SECRET=${OAUTH2_PROXY_COOKIE_SECRET}
OAUTH2_PROXY_REDIRECT_URL=https://homelab.lan:8444/oauth2/callback
OIDC_ISSUER_URL=https://homelab.lan:8444/keycloak/realms/comfyui

# Keycloak Bootstrap Admin (for Keycloak admin console at /keycloak/admin/)
KEYCLOAK_BOOTSTRAP_ADMIN_USERNAME=kcadmin
KEYCLOAK_BOOTSTRAP_ADMIN_PASSWORD=${KEYCLOAK_BOOTSTRAP_ADMIN_PASSWORD}

# Keycloak PostgreSQL Database
KEYCLOAK_DB_NAME=keycloak
KEYCLOAK_DB_USER=keycloak
KEYCLOAK_DB_PASSWORD=${KEYCLOAK_DB_PASSWORD}

# Baseline Realm Users (passwords are temporary, users must change on first login)
SSO_EMAIL_DOMAIN=homelab.lan
SSO_ADMIN_PASS=${SSO_ADMIN_PASS}
SSO_USER1_PASS=${SSO_USER1_PASS}
SSO_USER2_PASS=${SSO_USER2_PASS}

# Email Allowlist (comma-separated, or use * for all)
SSO_ALLOWED_EMAILS=admin@homelab.lan,user1@homelab.lan,user2@homelab.lan
EOF

echo "✅ SSO configuration added to $ENV_FILE"

# Create oauth2-proxy config directory
echo "[3/6] Creating OAuth2-Proxy configuration..."
mkdir -p config/oauth2-proxy

cat > config/oauth2-proxy/oauth2-proxy.cfg << 'EOF'
# OAuth2 Proxy Configuration for Keycloak OIDC
proxy_prefix = "/oauth2"
upstreams = ["file:///dev/null"]
reverse_proxy = true
set_xauthrequest = true
skip_provider_button = true

# Healthcheck endpoint
ping_path = "/oauth2/ping"

# Email validation
authenticated_emails_file = "/etc/oauth2-proxy/allowed_emails.txt"
email_domains = ["*"]

# Session settings
cookie_secure = true
cookie_httponly = true
cookie_samesite = "lax"
session_store_type = "cookie"

# Logging
request_logging = true
auth_logging = true
EOF

cat > config/oauth2-proxy/allowed_emails.txt << EOF
admin@homelab.lan
user1@homelab.lan
user2@homelab.lan
EOF

echo "✅ OAuth2-Proxy configuration files created"

# Generate Keycloak realm import file
echo "[4/6] Generating Keycloak realm import file..."
source "$ENV_FILE"

# Escape special characters for sed
escape_sed() {
    printf '%s\n' "$1" | sed -e 's/[\/&]/\\&/g'
}

ESCAPED_CLIENT_SECRET=$(escape_sed "$OAUTH2_PROXY_CLIENT_SECRET")
ESCAPED_STACK_FQDN=$(escape_sed "$STACK_FQDN")
ESCAPED_NGINX_SSL_PORT=$(escape_sed "$NGINX_SSL_PORT")
ESCAPED_SSO_EMAIL_DOMAIN=$(escape_sed "$SSO_EMAIL_DOMAIN")
ESCAPED_SSO_ADMIN_PASS=$(escape_sed "$SSO_ADMIN_PASS")
ESCAPED_SSO_USER1_PASS=$(escape_sed "$SSO_USER1_PASS")
ESCAPED_SSO_USER2_PASS=$(escape_sed "$SSO_USER2_PASS")

sed \
  -e "s/__OAUTH2_PROXY_CLIENT_SECRET__/${ESCAPED_CLIENT_SECRET}/g" \
  -e "s/__STACK_FQDN__/${ESCAPED_STACK_FQDN}/g" \
  -e "s/__NGINX_SSL_PORT__/${ESCAPED_NGINX_SSL_PORT}/g" \
  -e "s/__SSO_EMAIL_DOMAIN__/${ESCAPED_SSO_EMAIL_DOMAIN}/g" \
  -e "s/__SSO_ADMIN_PASS__/${ESCAPED_SSO_ADMIN_PASS}/g" \
  -e "s/__SSO_USER1_PASS__/${ESCAPED_SSO_USER1_PASS}/g" \
  -e "s/__SSO_USER2_PASS__/${ESCAPED_SSO_USER2_PASS}/g" \
  config/keycloak/realm-comfyui.json.template > config/keycloak/realm-comfyui.json

chmod 600 config/keycloak/realm-comfyui.json
echo "✅ Keycloak realm file generated"

# Print credential summary
echo
echo "[5/6] =========================================="
echo "       SSO CREDENTIALS SUMMARY"
echo "=========================================="
echo
echo "🔐 Keycloak Admin Console:"
echo "   URL:      https://homelab.lan:8444/keycloak/admin/"
echo "   Username: kcadmin"
echo "   Password: ${KEYCLOAK_BOOTSTRAP_ADMIN_PASSWORD}"
echo
echo "👤 Baseline Users (must change password on first login):"
echo "   Admin:"
echo "     Email:    admin@homelab.lan"
echo "     Password: ${SSO_ADMIN_PASS}"
echo "     Roles:    comfyui_admin"
echo "     Note:     Will require TOTP setup on first login"
echo
echo "   User1:"
echo "     Email:    user1@homelab.lan"
echo "     Password: ${SSO_USER1_PASS}"
echo "     Roles:    comfyui_user"
echo
echo "   User2:"
echo "     Email:    user2@homelab.lan"
echo "     Password: ${SSO_USER2_PASS}"
echo "     Roles:    comfyui_user"
echo
echo "=========================================="
echo

# Save credentials to secure file
CREDS_FILE=".sso-credentials-$(date +%Y%m%d-%H%M%S).txt"
cat > "$CREDS_FILE" << EOF
SSO Setup Credentials
Generated: $(date -u +"%Y-%m-%d %H:%M:%S UTC")

Keycloak Admin Console:
  URL:      https://homelab.lan:8444/keycloak/admin/
  Username: kcadmin
  Password: ${KEYCLOAK_BOOTSTRAP_ADMIN_PASSWORD}

Baseline Users:
  Admin:
    Email:    admin@homelab.lan
    Password: ${SSO_ADMIN_PASS}
  
  User1:
    Email:    user1@homelab.lan
    Password: ${SSO_USER1_PASS}
  
  User2:
    Email:    user2@homelab.lan
    Password: ${SSO_USER2_PASS}

OAuth2 Proxy Secrets:
  Cookie Secret: ${OAUTH2_PROXY_COOKIE_SECRET}
  Client Secret: ${OAUTH2_PROXY_CLIENT_SECRET}

Database:
  Keycloak DB Password: ${KEYCLOAK_DB_PASSWORD}
EOF

chmod 600 "$CREDS_FILE"
echo "📝 Credentials saved to: $CREDS_FILE (keep this secure!)"
echo

echo "[6/6] Next steps:"
echo "  1. Review the updated $ENV_FILE"
echo "  2. Deploy with: bash tools/deploy-homelab.sh"
echo "  3. Access Keycloak at: https://homelab.lan:8444/keycloak/admin/"
echo "  4. Login with baseline users at: https://homelab.lan:8444/"
echo
echo "✅ SSO setup complete!"
